name: Reusable Workflow Caller

on:
  push:
    branches:
      - main

jobs:
  call-workflow-A:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Reusable Workflow
        uses: ./.github/workflows/resusable-workflow-called.yml  # Reference the local reusable workflow template
        with:
          username: akramewu
        secrets:
          token: ${{ secrets.TOKEN }}
