name: 080-resusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: akramewu/reusable-workflow/.github/workflows/reusable-workflow-called.yml@main
    with:
      username: Houssem
    secrets:
      token: ${{ secrets.TOKEN }}
          