name: reusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: ./.github/workflows/reusable-workflow-called.yml
          
    with:
      username: akramewu
    secrets:
      token: ${{ secrets.TOKEN }}

